title: Zebende package - performance comparison
description: Comparing performance of the Zebende Package with other Python and R packages that calculates the PDCCA coefficient
theme: jekyll-theme-slate
